### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cameron-sjo** [ernilos/PokemonGoApi#1]
Can you add a license please?

**Comment by ernilos** [comment]
Actually, my knowledge about license types is barely null. I'll take a look, but if you could give me some advice it would be grateful

**Comment by ardaozkal** [comment]
@ernilos try this, github supports it: http://choosealicense.com/

**Comment by ernilos** [comment]
I didn't know that if I don't provide a license copyright is applied, thanks for the information. I'm going to add the MIT License, as seems the best one for this project.

**Comment by ardaozkal** [comment]
Name it `LICENSE` please, not `MIT-license.md`. (doesn't really matter but could be confused by some)
